version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - microservices-net

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
